version: '2'
services:
  # development container that will pick up the code syncs
  sagemaker-tensorflow-serving-container-dev:
    image: 520713654638.dkr.ecr.us-west-2.amazonaws.com/sagemaker-tensorflow-serving:1.12-cpu
    volumes:
      - sagemaker-tensorflow-serving-container-native-osx-sync:/sagemaker:nocopy
      - ${PWD}/../../test/resources/models:/opt/ml/model/
    environment:
      - SAGEMAKER_TFS_DEFAULT_MODEL_NAME=half_plus_three
      - SAGEMAKER_TFS_NGINX_LOGLEVEL=error
      - SAGEMAKER_BIND_TO_PORT=8080
      - SAGEMAKER_SAFE_PORT_RANGE=9000-9999
      - GUNICORN_PORT=5000
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
    command: bash

# the containers that handle syncing our src code
volumes:
  sagemaker-tensorflow-serving-container-native-osx-sync:
    external: true
